/*
 * PanelCalcParms.java
 *
 * Created on January 16, 2008, 3:51 PM
 */

package edu.mbl.jif.ps.ui;

import edu.mbl.jif.ps.PSCalcModel;
import edu.mbl.jif.ps.PSCalcModel;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author  GBH
 */
public class PanelPSCalcParms extends javax.swing.JPanel {
    
    
    /** Creates new form PanelCalcParms */
    public PanelPSCalcParms() {
        initComponents();
    }
    public PanelPSCalcParms(PSCalcModel psm) {
        setPSCalcModel(psm);
        initComponents();
    }
    
    protected PSCalcModel pSCalcModel;
    public static final String PROP_PSCALCMODEL = "pSCalcModel";

    public PSCalcModel getPSCalcModel() {
        return pSCalcModel;
    }

    public void setPSCalcModel(PSCalcModel pSCalcModel) {
        PSCalcModel oldPSCalcModel = this.pSCalcModel;
        this.pSCalcModel = pSCalcModel;
        propertyChangeSupport.firePropertyChange(PROP_PSCALCMODEL, oldPSCalcModel, pSCalcModel);
    }

    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    spinWavelength = new javax.swing.JSpinner();
    jLabel2 = new javax.swing.JLabel();
    spinSwing = new javax.swing.JSpinner();
    jLabel3 = new javax.swing.JLabel();
    spinRefAngle = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    spinZeroIntensity = new javax.swing.JSpinner();
    jLabel5 = new javax.swing.JLabel();
    spinnerCeiling = new javax.swing.JSpinner();
    jPanel2 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    checkboxAutoCalc = new javax.swing.JCheckBox();
    checkboxMirrorInPath = new javax.swing.JCheckBox();
    checkBoxFastCalc = new javax.swing.JCheckBox();
    labelPlugin = new javax.swing.JLabel();
    valueAlgorithm = new javax.swing.JLabel();

    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
    jPanel1.setMaximumSize(new java.awt.Dimension(138, 100));
    jPanel1.setMinimumSize(new java.awt.Dimension(138, 100));
    jPanel1.setOpaque(false);
    jPanel1.setPreferredSize(new java.awt.Dimension(138, 100));
    jPanel1.setLayout(new java.awt.GridLayout(5, 2));

    jLabel1.setText("Wavelength");
    jPanel1.add(jLabel1);

    spinWavelength.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(10.0d)));

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.wavelength}"), spinWavelength, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    jPanel1.add(spinWavelength);

    jLabel2.setText("Swing");
    jPanel1.add(jLabel2);

    spinSwing.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.01d)));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.swingFraction}"), spinSwing, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    jPanel1.add(spinSwing);

    jLabel3.setText("Ref. Angle");
    jPanel1.add(jLabel3);

    spinRefAngle.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.refAngle}"), spinRefAngle, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    jPanel1.add(spinRefAngle);

    jLabel4.setText("ZeroIntensity");
    jPanel1.add(jLabel4);

    spinZeroIntensity.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.zeroIntensity}"), spinZeroIntensity, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    jPanel1.add(spinZeroIntensity);

    jLabel5.setText("Ceiling");
    jPanel1.add(jLabel5);

    spinnerCeiling.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));
    spinnerCeiling.setToolTipText("Retardance ceiling");

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.retCeiling}"), spinnerCeiling, org.jdesktop.beansbinding.BeanProperty.create("value"));
    bindingGroup.addBinding(binding);

    jPanel1.add(spinnerCeiling);

    add(jPanel1);

    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
    jPanel2.setOpaque(false);
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

    jLabel6.setText("Values to IJ_Prefs");
    jPanel2.add(jLabel6);

    checkboxAutoCalc.setText("AutoCalc");
    checkboxAutoCalc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    checkboxAutoCalc.setOpaque(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.autoCalc}"), checkboxAutoCalc, org.jdesktop.beansbinding.BeanProperty.create("selected"));
    bindingGroup.addBinding(binding);

    jPanel2.add(checkboxAutoCalc);

    checkboxMirrorInPath.setText("Mirror in path");
    checkboxMirrorInPath.setOpaque(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.mirrorInPath}"), checkboxMirrorInPath, org.jdesktop.beansbinding.BeanProperty.create("selected"));
    bindingGroup.addBinding(binding);

    jPanel2.add(checkboxMirrorInPath);

    checkBoxFastCalc.setText("FastCalc");
    checkBoxFastCalc.setToolTipText("Use fast approximation");
    checkBoxFastCalc.setOpaque(false);

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.fastCalc}"), checkBoxFastCalc, org.jdesktop.beansbinding.BeanProperty.create("selected"));
    bindingGroup.addBinding(binding);

    jPanel2.add(checkBoxFastCalc);

    labelPlugin.setText("Plugin to run:");
    jPanel2.add(labelPlugin);

    valueAlgorithm.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

    binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${PSCalcModel.calcPlugin}"), valueAlgorithm, org.jdesktop.beansbinding.BeanProperty.create("text"));
    bindingGroup.addBinding(binding);

    jPanel2.add(valueAlgorithm);

    add(jPanel2);

    bindingGroup.bind();
  }// </editor-fold>//GEN-END:initComponents
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkBoxFastCalc;
  private javax.swing.JCheckBox checkboxAutoCalc;
  private javax.swing.JCheckBox checkboxMirrorInPath;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel labelPlugin;
  private javax.swing.JSpinner spinRefAngle;
  private javax.swing.JSpinner spinSwing;
  private javax.swing.JSpinner spinWavelength;
  private javax.swing.JSpinner spinZeroIntensity;
  private javax.swing.JSpinner spinnerCeiling;
  private javax.swing.JLabel valueAlgorithm;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables
    
}
