/*
 * PanelConfig.java
 *
 * Created on February 7, 2008, 9:09 AM
 */

package edu.mbl.jif.stage;

/**
 *
 * @author  GBH
 */
public class PanelConfigStageXY extends javax.swing.JPanel {
    
    /** Creates new form PanelConfig */
    public PanelConfigStageXY() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSettingsMove = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinIncrement = new javax.swing.JSpinner();
        spinSettleTime = new javax.swing.JSpinner();
        panelBacklash = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinBacklashX = new javax.swing.JSpinner();
        spinPreSteps = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spinBacklashY = new javax.swing.JSpinner();
        buttonCalibrateScreenToStage = new javax.swing.JButton();
        buttonMeasure = new javax.swing.JButton();
        panelLimits = new javax.swing.JPanel();
        panelLimitXY1 = new edu.mbl.jif.gui.spatial.PanelLimitXY();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 222, 191));

        panelSettingsMove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSettingsMove.setOpaque(false);

        jLabel1.setText("nm / increment");

        jLabel5.setText("Settling Time");

        javax.swing.GroupLayout panelSettingsMoveLayout = new javax.swing.GroupLayout(panelSettingsMove);
        panelSettingsMove.setLayout(panelSettingsMoveLayout);
        panelSettingsMoveLayout.setHorizontalGroup(
            panelSettingsMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsMoveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSettingsMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(spinIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spinSettleTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSettingsMoveLayout.setVerticalGroup(
            panelSettingsMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsMoveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinSettleTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelBacklash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBacklash.setOpaque(false);

        jLabel2.setText("X-backlash");

        jLabel4.setText("Pre-steps");

        jLabel6.setText("Y-backlash");

        buttonCalibrateScreenToStage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonCalibrateScreenToStage.setText("Calibrate");
        buttonCalibrateScreenToStage.setToolTipText("Calibrate Screen to XY-Stage");
        buttonCalibrateScreenToStage.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonCalibrateScreenToStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalibrateScreenToStageActionPerformed(evt);
            }
        });

        buttonMeasure.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        buttonMeasure.setText("Measure");
        buttonMeasure.setToolTipText("Measure backlash");
        buttonMeasure.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonMeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMeasureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBacklashLayout = new javax.swing.GroupLayout(panelBacklash);
        panelBacklash.setLayout(panelBacklashLayout);
        panelBacklashLayout.setHorizontalGroup(
            panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacklashLayout.createSequentialGroup()
                .addGroup(panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBacklashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(spinBacklashX))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBacklashLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinPreSteps))
                    .addGroup(panelBacklashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(spinBacklashY))
                    .addGroup(panelBacklashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonCalibrateScreenToStage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMeasure)))
                .addContainerGap())
        );
        panelBacklashLayout.setVerticalGroup(
            panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBacklashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinBacklashX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinBacklashY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCalibrateScreenToStage)
                    .addComponent(buttonMeasure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBacklashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinPreSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        panelLimits.setOpaque(false);
        panelLimits.setLayout(new java.awt.BorderLayout());
        panelLimits.add(panelLimitXY1, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Limits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSettingsMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBacklash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLimits, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4)
                                .addComponent(panelLimits, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelBacklash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSettingsMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void buttonCalibrateScreenToStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalibrateScreenToStageActionPerformed
		new CalibratorStageXY().getPointsForCoord();
	}//GEN-LAST:event_buttonCalibrateScreenToStageActionPerformed

	private void buttonMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMeasureActionPerformed
		new CalibratorStageXY().doAcquireStagePositionSeries();
	}//GEN-LAST:event_buttonMeasureActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalibrateScreenToStage;
    private javax.swing.JButton buttonMeasure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelBacklash;
    private edu.mbl.jif.gui.spatial.PanelLimitXY panelLimitXY1;
    private javax.swing.JPanel panelLimits;
    private javax.swing.JPanel panelSettingsMove;
    private javax.swing.JSpinner spinBacklashX;
    private javax.swing.JSpinner spinBacklashY;
    private javax.swing.JSpinner spinIncrement;
    private javax.swing.JSpinner spinPreSteps;
    private javax.swing.JSpinner spinSettleTime;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        
    }
}
