/*
 * PanelConfig.java
 *
 * Created on February 7, 2008, 9:09 AM
 */
package edu.mbl.jif.stage;

import com.jgoodies.binding.adapter.SpinnerAdapterFactory;
import com.jgoodies.binding.beans.PropertyAdapter;
import edu.mbl.jif.camacq.InstrumentController;

/**
 *
 * @author  GBH
 */
public class PanelConfigStageZ extends javax.swing.JPanel {

  InstrumentController instrumentCtrl;
  StageZModel zModel;

  /** Creates new form PanelConfig */
  public PanelConfigStageZ(InstrumentController instrumentCtrl) {
    this.instrumentCtrl = instrumentCtrl;
    zModel = (StageZModel) instrumentCtrl.getModel("zstage");
    initComponents();
    spinNmPerIncrement.setModel(SpinnerAdapterFactory.createNumberAdapter(
            new PropertyAdapter(
            zModel, StageZModel.PROPERTYNAME_NMPERINCREMENT, true),
            zModel.getNmPerIncrement(), 1, 1000, 10));
    spinSettleTime.setModel(SpinnerAdapterFactory.createNumberAdapter(
            new PropertyAdapter(
            zModel, StageZModel.PROPERTYNAME_SETTLEDELAY, true),
            zModel.getSettleDelay(), 0, 1000, 1));
    spinBacklash.setModel(SpinnerAdapterFactory.createNumberAdapter(
            new PropertyAdapter(
            zModel, StageZModel.PROPERTYNAME_BACKLASH, true),
            zModel.getBacklash(), 0.0, 1000.0, 1.0));
    spinPreSteps.setModel(SpinnerAdapterFactory.createNumberAdapter(
            new PropertyAdapter(
            zModel, StageZModel.PROPERTYNAME_PRESTEPS, true),
            zModel.getPreSteps(), 0, 1000, 1));
    spinPreviewDelay.setModel(SpinnerAdapterFactory.createNumberAdapter(
            new PropertyAdapter(
            zModel, StageZModel.PROPERTYNAME_PREVIEWDELAY, true),
            zModel.getPreviewDelay(), 0, 1000, 100));

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelSettingsMove = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    spinNmPerIncrement = new javax.swing.JSpinner();
    jLabel5 = new javax.swing.JLabel();
    spinSettleTime = new javax.swing.JSpinner();
    jLabel2 = new javax.swing.JLabel();
    spinBacklash = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    spinPreSteps = new javax.swing.JSpinner();
    jLabel7 = new javax.swing.JLabel();
    spinPreviewDelay = new javax.swing.JSpinner();
    panelLimits = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    buttonLimitTop = new javax.swing.JButton();
    buttonLimitBottom = new javax.swing.JButton();

    setBackground(new java.awt.Color(220, 222, 191));

    panelSettingsMove.setOpaque(false);
    panelSettingsMove.setLayout(new java.awt.GridLayout(6, 2));

    jLabel1.setText("nm / increment");
    panelSettingsMove.add(jLabel1);
    panelSettingsMove.add(spinNmPerIncrement);

    jLabel5.setText("Settling Time");
    panelSettingsMove.add(jLabel5);
    panelSettingsMove.add(spinSettleTime);

    jLabel2.setText("Backlash");
    panelSettingsMove.add(jLabel2);
    panelSettingsMove.add(spinBacklash);

    jLabel4.setText("Pre-steps");
    panelSettingsMove.add(jLabel4);
    panelSettingsMove.add(spinPreSteps);

    jLabel7.setText("PreviewDelay");
    panelSettingsMove.add(jLabel7);
    panelSettingsMove.add(spinPreviewDelay);

    panelLimits.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel3.setText("Limits");
    panelLimits.add(jLabel3);

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

    buttonLimitTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/stage/icons/setStopTop.gif"))); // NOI18N
    buttonLimitTop.setEnabled(false);
    buttonLimitTop.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jPanel4.add(buttonLimitTop);

    buttonLimitBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/stage/icons/setStopBottom.gif"))); // NOI18N
    buttonLimitBottom.setEnabled(false);
    buttonLimitBottom.setMargin(new java.awt.Insets(0, 0, 0, 0));
    jPanel4.add(buttonLimitBottom);

    panelLimits.add(jPanel4);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelSettingsMove, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelLimits, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(panelLimits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
          .addComponent(panelSettingsMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonLimitBottom;
  private javax.swing.JButton buttonLimitTop;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel panelLimits;
  private javax.swing.JPanel panelSettingsMove;
  private javax.swing.JSpinner spinBacklash;
  private javax.swing.JSpinner spinNmPerIncrement;
  private javax.swing.JSpinner spinPreSteps;
  private javax.swing.JSpinner spinPreviewDelay;
  private javax.swing.JSpinner spinSettleTime;
  // End of variables declaration//GEN-END:variables
}
