/*
 * TestXYLogView.java
 *
 * Created on February 17, 2009, 5:47 PM
 */

package edu.mbl.jif.stage;

/**
 *
 * @author  GBH
 */
public class TestXYLogView extends javax.swing.JFrame {

    /** Creates new form TestXYLogView */
    public TestXYLogView() {
        initComponents();
        xYPositionLogPanel1.update(0.9,0.9);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xYPositionLogPanel1 = new edu.mbl.jif.stage.XYPositionLogPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout xYPositionLogPanel1Layout = new javax.swing.GroupLayout(xYPositionLogPanel1);
        xYPositionLogPanel1.setLayout(xYPositionLogPanel1Layout);
        xYPositionLogPanel1Layout.setHorizontalGroup(
            xYPositionLogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        xYPositionLogPanel1Layout.setVerticalGroup(
            xYPositionLogPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(xYPositionLogPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestXYLogView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.mbl.jif.stage.XYPositionLogPanel xYPositionLogPanel1;
    // End of variables declaration//GEN-END:variables

}
