/*
 * PanelSLM.java
 *
 * Created on November 20, 2007, 10:51 AM
 */
package edu.mbl.jif.varilc.sap;

import edu.mbl.jif.varilc.*;
import edu.mbl.jif.camacq.InstrumentController;
import javax.swing.SwingUtilities;

/**
 *
 * @author  GBH
 */
public class PanelSLM
        extends javax.swing.JPanel {

    SLM_Main slmm;
    private final InstrumentController ctrl;
    private int setValue;
    SLMController slmCtrl;


    public PanelSLM(InstrumentController ctrl) {
        this.ctrl = ctrl;
        this.slmm = (SLM_Main) ctrl.getModel("slm");
        slmCtrl = slmm.getController();
        initComponents();
        setSlmModel(slmm.slmModel);
    }

    /* ----- slmModel ----------------------------------------------*/

    private edu.mbl.jif.varilc.sap.SLMModel slmModel;
    public static final String PROP_SLMMODEL = "slmModel";


    public edu.mbl.jif.varilc.sap.SLMModel getSlmModel() {
        return this.slmModel;
    }


    public void setSlmModel(edu.mbl.jif.varilc.sap.SLMModel newslmModel) {
        edu.mbl.jif.varilc.sap.SLMModel oldslmModel = slmModel;
        this.slmModel = newslmModel;
        propertyChangeSupport.firePropertyChange(PROP_SLMMODEL, oldslmModel,
                newslmModel);
    }


    private java.beans.PropertyChangeSupport propertyChangeSupport = new java.beans.PropertyChangeSupport(this);


    public void addPropertyChangeListener(java.beans.PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }


    public void removePropertyChangeListener(java.beans.PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelPort = new javax.swing.JPanel();
        buttonPortSettings = new javax.swing.JButton();
        buttonMonitor = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        buttonExercise = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        panelCharacterize = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonCharacterizeElliptical = new javax.swing.JButton();
        buttonCharacterizeElliptical1 = new javax.swing.JButton();
        buttonCharacterizeRetarderA = new javax.swing.JButton();
        buttonCharacterizeRetarderB = new javax.swing.JButton();
        buttonFindExtinction = new javax.swing.JButton();
        panelLayers = new javax.swing.JPanel();
        sliderSetValue = new javax.swing.JSlider();
        buttonSetAll = new javax.swing.JButton();
        valueSetting = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        buttonSetAllEllip = new javax.swing.JButton();
        valueElliptical = new javax.swing.JLabel();
        buttonElipMin = new javax.swing.JButton();
        buttonElipMax = new javax.swing.JButton();
        buttonSetAllCircular = new javax.swing.JButton();
        valueCircular = new javax.swing.JLabel();
        buttonCircMin = new javax.swing.JButton();
        buttonCircMax = new javax.swing.JButton();
        buttonSetAllRetA = new javax.swing.JButton();
        valueRetarderA = new javax.swing.JLabel();
        buttonRetAMin = new javax.swing.JButton();
        buttonRetAMax = new javax.swing.JButton();
        buttonSetAllRetB = new javax.swing.JButton();
        valueRetarderB = new javax.swing.JLabel();
        buttonRetBMin = new javax.swing.JButton();
        buttonRetBMax = new javax.swing.JButton();
        buttonFullTransmission = new javax.swing.JButton();
        buttonMeasureRois = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonRestore = new javax.swing.JButton();
        buttonShowSettings = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        buttonShowRois = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        buttonElliptical = new javax.swing.JButton();
        buttonCircular = new javax.swing.JButton();
        buttonCalibMasks = new javax.swing.JButton();
        buttonCalibRetarders = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonNorth = new javax.swing.JButton();
        buttonSouth = new javax.swing.JButton();
        buttonEast = new javax.swing.JButton();
        buttonWest = new javax.swing.JButton();
        buttonCenter = new javax.swing.JButton();
        buttonOpenMasks = new javax.swing.JButton();
        buttonCloseMasks = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        checkAll = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        comboSector = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        spinA = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spinB = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelAdjustment1 = new edu.mbl.jif.varilc.sap.PanelAdjustment();

        setBackground(new java.awt.Color(198, 178, 218));

        jTabbedPane1.setBackground(new java.awt.Color(213, 202, 223));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        panelPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Serial Port"));

        buttonPortSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/comm/icons/usb16.png"))); // NOI18N
        buttonPortSettings.setToolTipText("Port Settings"); // NOI18N
        buttonPortSettings.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonPortSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPortSettingsActionPerformed(evt);
            }
        });

        buttonMonitor.setText("Monitor"); // NOI18N
        buttonMonitor.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPortLayout = new javax.swing.GroupLayout(panelPort);
        panelPort.setLayout(panelPortLayout);
        panelPortLayout.setHorizontalGroup(
            panelPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPortSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPortLayout.setVerticalGroup(
            panelPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPortLayout.createSequentialGroup()
                .addComponent(buttonPortSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMonitor)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonExercise.setText("Exercise"); // NOI18N
        buttonExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExerciseActionPerformed(evt);
            }
        });

        buttonReset.setText("Reset"); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonExercise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExercise)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Wavelength");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.wavelength}"), jSpinner1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.swing}"), jSpinner2, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("Swing");

        jLabel5.setText("SettleTime");

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.settlingtime}"), jSpinner3, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("ZeroIntensity");

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.zeroIntensity}"), jSpinner4, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelPort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Config", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Characterize"));

        buttonCharacterizeElliptical.setText("Elliptical"); // NOI18N
        buttonCharacterizeElliptical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCharacterizeEllipticalActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCharacterizeElliptical);

        buttonCharacterizeElliptical1.setText("Circular"); // NOI18N
        buttonCharacterizeElliptical1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCharacterizeCircularActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCharacterizeElliptical1);

        buttonCharacterizeRetarderA.setText("RetarderA"); // NOI18N
        buttonCharacterizeRetarderA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCharacterizeRetarderAActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCharacterizeRetarderA);

        buttonCharacterizeRetarderB.setText("RetarderB"); // NOI18N
        buttonCharacterizeRetarderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCharacterizeRetarderBActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCharacterizeRetarderB);

        buttonFindExtinction.setText("Find Extinction");
        buttonFindExtinction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFindExtinctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCharacterizeLayout = new javax.swing.GroupLayout(panelCharacterize);
        panelCharacterize.setLayout(panelCharacterizeLayout);
        panelCharacterizeLayout.setHorizontalGroup(
            panelCharacterizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCharacterizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFindExtinction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        panelCharacterizeLayout.setVerticalGroup(
            panelCharacterizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCharacterizeLayout.createSequentialGroup()
                .addGroup(panelCharacterizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCharacterizeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonFindExtinction))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCharacterizeLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Characterize", panelCharacterize);

        panelLayers.setOpaque(false);

        sliderSetValue.setMaximum(4095);
        sliderSetValue.setOpaque(false);
        sliderSetValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSetValueStateChanged(evt);
            }
        });

        buttonSetAll.setText("All"); // NOI18N
        buttonSetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetAllActionPerformed(evt);
            }
        });

        valueSetting.setText("-"); // NOI18N

        jPanel7.setLayout(new java.awt.GridLayout(4, 4));

        buttonSetAllEllip.setText("Elliptical"); // NOI18N
        buttonSetAllEllip.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSetAllEllip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetAllEllipActionPerformed(evt);
            }
        });
        jPanel7.add(buttonSetAllEllip);

        valueElliptical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueElliptical.setText("-"); // NOI18N
        jPanel7.add(valueElliptical);

        buttonElipMin.setText("Min"); // NOI18N
        buttonElipMin.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonElipMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElipMinActionPerformed(evt);
            }
        });
        jPanel7.add(buttonElipMin);

        buttonElipMax.setText("Max"); // NOI18N
        buttonElipMax.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonElipMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElipMaxActionPerformed(evt);
            }
        });
        jPanel7.add(buttonElipMax);

        buttonSetAllCircular.setText("Circular"); // NOI18N
        buttonSetAllCircular.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSetAllCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetAllCircularActionPerformed(evt);
            }
        });
        jPanel7.add(buttonSetAllCircular);

        valueCircular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueCircular.setText("-"); // NOI18N
        jPanel7.add(valueCircular);

        buttonCircMin.setText("Min"); // NOI18N
        buttonCircMin.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonCircMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCircMinActionPerformed(evt);
            }
        });
        jPanel7.add(buttonCircMin);

        buttonCircMax.setText("Max"); // NOI18N
        buttonCircMax.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonCircMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCircMaxActionPerformed(evt);
            }
        });
        jPanel7.add(buttonCircMax);

        buttonSetAllRetA.setText("RetarderA"); // NOI18N
        buttonSetAllRetA.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSetAllRetA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetAllRetAActionPerformed(evt);
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(buttonSetAllRetA);

        valueRetarderA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueRetarderA.setText("-"); // NOI18N
        jPanel7.add(valueRetarderA);

        buttonRetAMin.setText("Min"); // NOI18N
        buttonRetAMin.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonRetAMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetAMinActionPerformed(evt);
            }
        });
        jPanel7.add(buttonRetAMin);

        buttonRetAMax.setText("Max"); // NOI18N
        buttonRetAMax.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonRetAMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetAMaxActionPerformed(evt);
            }
        });
        jPanel7.add(buttonRetAMax);

        buttonSetAllRetB.setText("RetarderB"); // NOI18N
        buttonSetAllRetB.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSetAllRetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetAllRetBActionPerformed(evt);
            }
        });
        jPanel7.add(buttonSetAllRetB);

        valueRetarderB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueRetarderB.setText("-"); // NOI18N
        jPanel7.add(valueRetarderB);

        buttonRetBMin.setText("Min"); // NOI18N
        buttonRetBMin.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonRetBMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetBMinActionPerformed(evt);
            }
        });
        jPanel7.add(buttonRetBMin);

        buttonRetBMax.setText("Max"); // NOI18N
        buttonRetBMax.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonRetBMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetBMaxActionPerformed(evt);
            }
        });
        jPanel7.add(buttonRetBMax);

        buttonFullTransmission.setText("FullXmiss"); // NOI18N
        buttonFullTransmission.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonFullTransmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFullTransmissionActionPerformed(evt);
            }
        });

        buttonMeasureRois.setText("Retarders");
        buttonMeasureRois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMeasureRoisActionPerformed(evt);
            }
        });

        jLabel2.setText("Measure:");

        javax.swing.GroupLayout panelLayersLayout = new javax.swing.GroupLayout(panelLayers);
        panelLayers.setLayout(panelLayersLayout);
        panelLayersLayout.setHorizontalGroup(
            panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayersLayout.createSequentialGroup()
                        .addComponent(sliderSetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valueSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayersLayout.createSequentialGroup()
                        .addComponent(jPanel7, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayersLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buttonMeasureRois))
                            .addGroup(panelLayersLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(buttonFullTransmission))))))
                .addGap(60, 60, 60))
        );
        panelLayersLayout.setVerticalGroup(
            panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valueSetting)
                        .addComponent(buttonSetAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderSetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayersLayout.createSequentialGroup()
                        .addComponent(buttonFullTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMeasureRois))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Layers", panelLayers);

        jPanel2.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(237, 221, 238));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Settings"); // NOI18N
        jPanel3.add(jLabel1);

        buttonSave.setText("Save"); // NOI18N
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSave);

        buttonRestore.setText("Restore"); // NOI18N
        buttonRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestoreActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRestore);

        buttonShowSettings.setText("Show");
        buttonShowSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowSettingsActionPerformed(evt);
            }
        });
        jPanel3.add(buttonShowSettings);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("TolCoarse");

        jLabel8.setText("TolFine");

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.tolCoarse}"), jSpinner5, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${slmModel.tolFine}"), jSpinner6, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonShowRois.setText("Show ROIs"); // NOI18N
        buttonShowRois.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonShowRois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowRoisActionPerformed(evt);
            }
        });

        jPanel5.setOpaque(false);

        buttonElliptical.setText("Elliptical"); // NOI18N
        jPanel5.add(buttonElliptical);

        buttonCircular.setText("Circular"); // NOI18N
        jPanel5.add(buttonCircular);

        buttonCalibMasks.setText("Masks"); // NOI18N
        buttonCalibMasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalibMasksActionPerformed(evt);
            }
        });
        jPanel5.add(buttonCalibMasks);

        buttonCalibRetarders.setText("Retarders"); // NOI18N
        buttonCalibRetarders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalibRetardersActionPerformed(evt);
            }
        });
        jPanel5.add(buttonCalibRetarders);

        jButton1.setText("Define Frames"); // NOI18N
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonShowRois)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(buttonShowRois)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Calibrate", jPanel2);

        jPanel8.setOpaque(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setOpaque(false);

        buttonNorth.setText("North"); // NOI18N
        buttonNorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNorthActionPerformed(evt);
            }
        });
        jPanel6.add(buttonNorth);

        buttonSouth.setText("South"); // NOI18N
        buttonSouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouthActionPerformed(evt);
            }
        });
        jPanel6.add(buttonSouth);

        buttonEast.setText("East"); // NOI18N
        buttonEast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEastActionPerformed(evt);
            }
        });
        jPanel6.add(buttonEast);

        buttonWest.setText("West"); // NOI18N
        buttonWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWestActionPerformed(evt);
            }
        });
        jPanel6.add(buttonWest);

        buttonCenter.setText("Center"); // NOI18N
        buttonCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCenterActionPerformed(evt);
            }
        });
        jPanel6.add(buttonCenter);

        buttonOpenMasks.setText("Open");
        buttonOpenMasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenMasksActionPerformed(evt);
            }
        });
        jPanel6.add(buttonOpenMasks);

        buttonCloseMasks.setText("Close");
        buttonCloseMasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseMasksActionPerformed(evt);
            }
        });
        jPanel6.add(buttonCloseMasks);

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(25);
        jSlider1.setMinimum(1);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(1);

        jLabel15.setText("Show Frame:");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(27, 27, 27)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Masks", jPanel8);

        jButton2.setText("Acquire");

        jCheckBox1.setText("Save");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jCheckBox1)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton2))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acquire", jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Manual Adjustment"));

        checkAll.setText("All");

        jLabel11.setText("Sector");

        comboSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        comboSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSectorActionPerformed(evt);
            }
        });

        jLabel14.setText("Retardance:");

        spinA.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(10)));
        spinA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinAStateChanged(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("A");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("B");

        spinB.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(10)));
        spinB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinBStateChanged(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("-");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("-");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(checkAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAll)
                    .addComponent(spinA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(154, 154, 154))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adjust", jPanel10);
        jTabbedPane1.addTab("tab8", panelAdjustment1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

  private void buttonMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonitorActionPerformed
    slmm.getController().openMonitor();
  }//GEN-LAST:event_buttonMonitorActionPerformed

  private void buttonPortSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPortSettingsActionPerformed
    if(slmm.getController().openPortSettingsDialog(false)) {
      try {
        slmm.getController().openConnection();
        new Thread(new Runnable() {
          public void run() {
            slmm.getController().initializeController();
          }
        }).start();
      } catch (Exception ex) {
        ex.printStackTrace();
      }
    }
  }//GEN-LAST:event_buttonPortSettingsActionPerformed

  private void buttonCharacterizeEllipticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCharacterizeEllipticalActionPerformed
      slmm.runResponseCurves(Layer.elliptical);
}//GEN-LAST:event_buttonCharacterizeEllipticalActionPerformed

  private void buttonExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExerciseActionPerformed
        slmm.exerciseAll();
  }//GEN-LAST:event_buttonExerciseActionPerformed

  private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
      //slmCtrl.checkForError();
      slmCtrl.resetError();
}//GEN-LAST:event_buttonResetActionPerformed

  private void sliderSetValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderSetValueStateChanged
      setValue = (int)((float)sliderSetValue.getModel().getValue());
      this.valueSetting.setText(String.valueOf(setValue));
}//GEN-LAST:event_sliderSetValueStateChanged

  private void buttonSetAllRetAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetAllRetAActionPerformed
     slmCtrl.setAllRetarderATo(setValue);
           valueRetarderA.setText(String.valueOf(setValue));
}//GEN-LAST:event_buttonSetAllRetAActionPerformed

  private void buttonSetAllRetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetAllRetBActionPerformed
      slmCtrl.setAllRetarderBTo(setValue);
      valueRetarderB.setText(String.valueOf(setValue));
  }//GEN-LAST:event_buttonSetAllRetBActionPerformed

  private void buttonSetAllCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetAllCircularActionPerformed
      slmCtrl.setAllCircularTo(setValue);
      valueCircular.setText(String.valueOf(setValue));
  }//GEN-LAST:event_buttonSetAllCircularActionPerformed

  private void buttonSetAllEllipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetAllEllipActionPerformed
      slmCtrl.setAllEllipticalTo(setValue);
      valueElliptical.setText(String.valueOf(setValue));
  }//GEN-LAST:event_buttonSetAllEllipActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void buttonSetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetAllActionPerformed
      slmCtrl.setAllTo(setValue);
      valueElliptical.setText(String.valueOf(setValue));
      valueCircular.setText(String.valueOf(setValue));
      valueRetarderA.setText(String.valueOf(setValue));
      valueRetarderB.setText(String.valueOf(setValue));
  }//GEN-LAST:event_buttonSetAllActionPerformed

  private void buttonShowRoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowRoisActionPerformed
      slmm.showROIs();
  }//GEN-LAST:event_buttonShowRoisActionPerformed

  private void buttonRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestoreActionPerformed
      slmm.restoreSettings();
  }//GEN-LAST:event_buttonRestoreActionPerformed

  private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
       slmm.saveSettings();
  }//GEN-LAST:event_buttonSaveActionPerformed

  private void buttonCharacterizeCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCharacterizeCircularActionPerformed
     slmm.runResponseCurves(Layer.circular);
}//GEN-LAST:event_buttonCharacterizeCircularActionPerformed

  private void buttonCharacterizeRetarderAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCharacterizeRetarderAActionPerformed
      slmm.runResponseCurves(Layer.retarderA);
  }//GEN-LAST:event_buttonCharacterizeRetarderAActionPerformed

  private void buttonCharacterizeRetarderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCharacterizeRetarderBActionPerformed
      slmm.runResponseCurves(Layer.retarderB);
  }//GEN-LAST:event_buttonCharacterizeRetarderBActionPerformed

  private void buttonNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNorthActionPerformed
      slmCtrl.setMask(Mask.North);
  }//GEN-LAST:event_buttonNorthActionPerformed

  private void buttonSouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouthActionPerformed
      slmCtrl.setMask(Mask.South);
  }//GEN-LAST:event_buttonSouthActionPerformed

  private void buttonEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEastActionPerformed
      slmCtrl.setMask(Mask.East);
  }//GEN-LAST:event_buttonEastActionPerformed

  private void buttonWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWestActionPerformed
      slmCtrl.setMask(Mask.West);
  }//GEN-LAST:event_buttonWestActionPerformed

  private void buttonCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCenterActionPerformed
      slmCtrl.setMask(Mask.Center);
  }//GEN-LAST:event_buttonCenterActionPerformed

  private void buttonCalibMasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalibMasksActionPerformed
      slmm.doCalibrateMasks();
  }//GEN-LAST:event_buttonCalibMasksActionPerformed

  private void buttonCalibRetardersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalibRetardersActionPerformed
      slmm.doCalibrateRetarders();
  }//GEN-LAST:event_buttonCalibRetardersActionPerformed

  private void buttonFullTransmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFullTransmissionActionPerformed
      slmCtrl.setFullTransmission();
  }//GEN-LAST:event_buttonFullTransmissionActionPerformed

  private void buttonElipMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElipMinActionPerformed
      slmCtrl.setEllipticalToMaskState(SLMController.allStates);
  }//GEN-LAST:event_buttonElipMinActionPerformed

  private void buttonElipMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElipMaxActionPerformed
      slmCtrl.setEllipticalToMaskState(SLMController.noneStates);
  }//GEN-LAST:event_buttonElipMaxActionPerformed

  private void buttonCircMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCircMinActionPerformed
      slmCtrl.setCircularToMaskState(SLMController.nietherStates);
  }//GEN-LAST:event_buttonCircMinActionPerformed

  private void buttonCircMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCircMaxActionPerformed
      slmCtrl.setCircularToMaskState(SLMController.bothStates);
  }//GEN-LAST:event_buttonCircMaxActionPerformed

  private void buttonRetAMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetAMinActionPerformed
     slmCtrl.setRetardersA(0);
  }//GEN-LAST:event_buttonRetAMinActionPerformed

  private void buttonRetAMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetAMaxActionPerformed
      slmCtrl.setRetardersA(1);
  }//GEN-LAST:event_buttonRetAMaxActionPerformed

  private void buttonRetBMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetBMinActionPerformed
     slmCtrl.setRetardersB(0); 
  }//GEN-LAST:event_buttonRetBMinActionPerformed

  private void buttonRetBMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetBMaxActionPerformed
           slmCtrl.setRetardersB(1); 
  }//GEN-LAST:event_buttonRetBMaxActionPerformed

  private void buttonFindExtinctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFindExtinctionActionPerformed
      SwingUtilities.invokeLater(new Runnable() {
          public void run() {
            slmm.findExtinction();
          }
      });

  }//GEN-LAST:event_buttonFindExtinctionActionPerformed

  private void buttonShowSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowSettingsActionPerformed
      slmCtrl.showSettings();
  }//GEN-LAST:event_buttonShowSettingsActionPerformed

  private void buttonMeasureRoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMeasureRoisActionPerformed
      SwingUtilities.invokeLater(new Runnable() {
          public void run() {
             slmm.measureROIsRetarders();
          }
      });

  }//GEN-LAST:event_buttonMeasureRoisActionPerformed

  private void spinBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinBStateChanged
       Integer set = (Integer) spinB.getModel().getValue();
       if(checkAll.isSelected()) {
            slmCtrl.setRetardersB(set);
       } else {
            slmCtrl.setRetB(comboSector.getSelectedIndex(), set);
       }
  }//GEN-LAST:event_spinBStateChanged

  private void spinAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinAStateChanged
       Integer set = (Integer) spinA.getModel().getValue();
       if(checkAll.isSelected()) {
            slmCtrl.setRetardersA(set);
       } else {
            slmCtrl.setRetA(comboSector.getSelectedIndex(), set);
       }
  }//GEN-LAST:event_spinAStateChanged

  private void comboSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSectorActionPerformed
      int sector = comboSector.getSelectedIndex();
      spinA.setValue(slmCtrl.getRetA(sector));
            spinB.setValue(slmCtrl.getRetB(sector));
  }//GEN-LAST:event_comboSectorActionPerformed

  private void buttonOpenMasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenMasksActionPerformed
      slmCtrl.setEllipticalToMaskState(SLMController.noneStates);
      slmCtrl.setCircularToMaskState(SLMController.nietherStates);
      
  }//GEN-LAST:event_buttonOpenMasksActionPerformed

  private void buttonCloseMasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseMasksActionPerformed
      slmCtrl.setEllipticalToMaskState(SLMController.allStates);
      slmCtrl.setCircularToMaskState(SLMController.bothStates);
  }//GEN-LAST:event_buttonCloseMasksActionPerformed

                                 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalibMasks;
    private javax.swing.JButton buttonCalibRetarders;
    private javax.swing.JButton buttonCenter;
    private javax.swing.JButton buttonCharacterizeElliptical;
    private javax.swing.JButton buttonCharacterizeElliptical1;
    private javax.swing.JButton buttonCharacterizeRetarderA;
    private javax.swing.JButton buttonCharacterizeRetarderB;
    private javax.swing.JButton buttonCircMax;
    private javax.swing.JButton buttonCircMin;
    private javax.swing.JButton buttonCircular;
    private javax.swing.JButton buttonCloseMasks;
    private javax.swing.JButton buttonEast;
    private javax.swing.JButton buttonElipMax;
    private javax.swing.JButton buttonElipMin;
    private javax.swing.JButton buttonElliptical;
    private javax.swing.JButton buttonExercise;
    private javax.swing.JButton buttonFindExtinction;
    private javax.swing.JButton buttonFullTransmission;
    private javax.swing.JButton buttonMeasureRois;
    private javax.swing.JButton buttonMonitor;
    private javax.swing.JButton buttonNorth;
    private javax.swing.JButton buttonOpenMasks;
    private javax.swing.JButton buttonPortSettings;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonRestore;
    private javax.swing.JButton buttonRetAMax;
    private javax.swing.JButton buttonRetAMin;
    private javax.swing.JButton buttonRetBMax;
    private javax.swing.JButton buttonRetBMin;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSetAll;
    private javax.swing.JButton buttonSetAllCircular;
    private javax.swing.JButton buttonSetAllEllip;
    private javax.swing.JButton buttonSetAllRetA;
    private javax.swing.JButton buttonSetAllRetB;
    private javax.swing.JButton buttonShowRois;
    private javax.swing.JButton buttonShowSettings;
    private javax.swing.JButton buttonSouth;
    private javax.swing.JButton buttonWest;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JComboBox comboSector;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private edu.mbl.jif.varilc.sap.PanelAdjustment panelAdjustment1;
    private javax.swing.JPanel panelCharacterize;
    private javax.swing.JPanel panelLayers;
    private javax.swing.JPanel panelPort;
    private javax.swing.JSlider sliderSetValue;
    private javax.swing.JSpinner spinA;
    private javax.swing.JSpinner spinB;
    private javax.swing.JLabel valueCircular;
    private javax.swing.JLabel valueElliptical;
    private javax.swing.JLabel valueRetarderA;
    private javax.swing.JLabel valueRetarderB;
    private javax.swing.JLabel valueSetting;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
