/*
 * PanelAdjustment.java
 *
 * Created on February 8, 2008, 10:10 AM
 */

package edu.mbl.jif.varilc.sap;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author  GBH
 */
public class PanelAdjustment extends javax.swing.JPanel implements FocusListener {
    
    /** Creates new form PanelAdjustment */
    public PanelAdjustment() {
        initComponents();
        this.addFocusListener(this);
    }
    
    SLMController slmCtrl;
    public PanelAdjustment(SLMController ctrl) {
        this.slmCtrl = ctrl;
        initComponents();
        this.addFocusListener(this);
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboEllip = new javax.swing.JComboBox();
        spinEllip = new javax.swing.JSpinner();
        buttonEllip = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboCirc = new javax.swing.JComboBox();
        spinCirc = new javax.swing.JSpinner();
        buttonCirc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboRetA = new javax.swing.JComboBox();
        spinRetA = new javax.swing.JSpinner();
        buttonRetA = new javax.swing.JButton();
        valueRetA = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        spinRetB = new javax.swing.JSpinner();
        buttonRetB = new javax.swing.JButton();
        valueRetB = new javax.swing.JLabel();
        comboRetB = new javax.swing.JComboBox();

        jLabel1.setText("Elliptical");

        comboEllip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        spinEllip.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4095, 1));

        buttonEllip.setText("all");
        buttonEllip.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(buttonEllip)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(buttonEllip)
                .addComponent(spinEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboEllip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Circular");

        comboCirc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        spinCirc.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4095, 1));

        buttonCirc.setText("all");
        buttonCirc.setMargin(new java.awt.Insets(2, 4, 2, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(buttonCirc)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(buttonCirc)
                .addComponent(spinCirc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboCirc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setText("Retarder A");

        comboRetA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        spinRetA.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4095, 1));

        buttonRetA.setText("all");
        buttonRetA.setMargin(new java.awt.Insets(2, 4, 2, 4));

        valueRetA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valueRetA.setText("0.000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(comboRetA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spinRetA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueRetA, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonRetA)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(buttonRetA)
                .addComponent(valueRetA)
                .addComponent(comboRetA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(spinRetA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setText("Retarder B");

        spinRetB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4095, 1));

        buttonRetB.setText("all");
        buttonRetB.setMargin(new java.awt.Insets(2, 4, 2, 4));

        valueRetB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valueRetB.setText("0.000");

        comboRetB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(comboRetB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spinRetB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valueRetB, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonRetB)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(buttonRetB)
                .addComponent(valueRetB)
                .addComponent(comboRetB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(spinRetB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCirc;
    private javax.swing.JButton buttonEllip;
    private javax.swing.JButton buttonRetA;
    private javax.swing.JButton buttonRetB;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JCheckBox checkAll1;
    private javax.swing.JCheckBox checkAll2;
    private javax.swing.JCheckBox checkAll3;
    private javax.swing.JComboBox comboCirc;
    private javax.swing.JComboBox comboEllip;
    private javax.swing.JComboBox comboRetA;
    private javax.swing.JComboBox comboRetB;
    private javax.swing.JComboBox comboSector;
    private javax.swing.JComboBox comboSector1;
    private javax.swing.JComboBox comboSector2;
    private javax.swing.JComboBox comboSector3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner spinCirc;
    private javax.swing.JSpinner spinEllip;
    private javax.swing.JSpinner spinRetA;
    private javax.swing.JSpinner spinRetB;
    private javax.swing.JLabel valueRetA;
    private javax.swing.JLabel valueRetB;
    // End of variables declaration//GEN-END:variables

  private void spinBStateChanged(javax.swing.event.ChangeEvent evt) {                                   
//       Double set = (Double) spinB.getModel().getValue();
//       if(checkAll.isSelected()) {
//            slmCtrl.setRetardersB(set);
//       } else {
//            slmCtrl.setRetB(comboSector.getSelectedIndex(), set);
//       }
  }                                  

  private void spinAStateChanged(javax.swing.event.ChangeEvent evt) {                                   
//       Double set = (Double) spinA.getModel().getValue();
//       if(checkAll.isSelected()) {
//            slmCtrl.setRetardersA(set);
//       } else {
//            slmCtrl.setRetA(comboSector.getSelectedIndex(), set);
//       }
  }                                  

  
  private void comboSectorActionPerformed(java.awt.event.ActionEvent evt) {                                            
      int sector = comboSector.getSelectedIndex();
      double setA = slmCtrl.currentlySetA[sector];
      double setB = slmCtrl.currentlySetB[sector];   
      //spinA.setValue(setA);
      //spinB.setValue(setB);                                           
  }    
    
  public void updateRetA() {
      int sector = comboRetA.getSelectedIndex()-1;
      int setting = slmCtrl.getRetA(sector);
      this.spinRetA.setValue(new Integer(setting));
      //slmCtrl.getRetardanceA(sector, setting)
      //this.valueRetA.setText(slmCtrl.getRetardanceA(sector, setting));
      
  }
    public void focusGained(FocusEvent e) {
      // update values
        System.out.println("focus gained on panel adjust");
    }


    public void focusLost(FocusEvent e) {
    }
    
}
