/*
 * PanelSequenceMonitor.java
 *
 * Created on August 27, 2006, 9:19 PM
 */
package edu.mbl.jif.acq;

import edu.mbl.jif.camera.Utils;
import edu.mbl.jif.gui.clock.CountdownClock;
import edu.mbl.jif.utils.StaticSwingUtils;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author  GBH
 */
public class PanelSequenceMonitor extends javax.swing.JPanel {

  SequenceController seqCtrl;
  CountdownClock clock;

  /** Creates new form PanelSequenceMonitor */
  public PanelSequenceMonitor(SequenceController seqCtrl) {
    this.seqCtrl = seqCtrl;
    initComponents();

    clock = new CountdownClock();
    clock.setBounds(15, 15, 75, 75);
    panelClock.add(clock);

    jProgressBar1.setMaximum(seqCtrl.getIntervals());
    // jProgressBar2.setMaximum(seqCtrl.getIntervals());

    buttonStart.setEnabled(seqCtrl.initialDelay <= 0);
    valueNumber.setText(String.valueOf(seqCtrl.getIntervals()));
    valueInterval.setText(String.valueOf(seqCtrl.getPeriod() / 1000));
    if (seqCtrl.initialDelay > 0) {
      labelCompleted.setText("Initial delay.  Waiting...");
    }
  }

  public void startSequence() {
    StaticSwingUtils.dispatchToEDT(new Runnable() {

      public void run() {
        buttonStart.setEnabled(false);
        buttonCancel.setEnabled(true);
      }
    });
    seqCtrl.startTimer();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelClock = new javax.swing.JPanel();
    panelButtons = new javax.swing.JPanel();
    buttonStart = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();
    panelTitle = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    labelInterval = new javax.swing.JLabel();
    valueInterval = new javax.swing.JLabel();
    valueNumber = new javax.swing.JLabel();
    panelStatus = new javax.swing.JPanel();
    jProgressBar1 = new javax.swing.JProgressBar();
    labalBegan = new javax.swing.JLabel();
    labelWillFinish = new javax.swing.JLabel();
    labelToGo = new javax.swing.JLabel();
    labelCompleted = new javax.swing.JLabel();
    jProgressBar2 = new javax.swing.JProgressBar();
    jProgressBar2.setOrientation(JProgressBar.VERTICAL);

    panelClock.setBorder(javax.swing.BorderFactory.createTitledBorder("Next:"));
    panelClock.setMinimumSize(new java.awt.Dimension(90, 90));
    panelClock.setPreferredSize(new java.awt.Dimension(90, 90));

    org.jdesktop.layout.GroupLayout panelClockLayout = new org.jdesktop.layout.GroupLayout(panelClock);
    panelClock.setLayout(panelClockLayout);
    panelClockLayout.setHorizontalGroup(
      panelClockLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 108, Short.MAX_VALUE)
    );
    panelClockLayout.setVerticalGroup(
      panelClockLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 79, Short.MAX_VALUE)
    );

    buttonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/acq/icons/action_go.gif"))); // NOI18N
    buttonStart.setText(" Start");
    buttonStart.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StartIt(evt);
      }
    });

    buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/acq/icons/cancel.png"))); // NOI18N
    buttonCancel.setText("Cancel");
    buttonCancel.setEnabled(false);
    buttonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CancelIt(evt);
      }
    });

    org.jdesktop.layout.GroupLayout panelButtonsLayout = new org.jdesktop.layout.GroupLayout(panelButtons);
    panelButtons.setLayout(panelButtonsLayout);
    panelButtonsLayout.setHorizontalGroup(
      panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, panelButtonsLayout.createSequentialGroup()
        .addContainerGap(252, Short.MAX_VALUE)
        .add(buttonStart)
        .add(47, 47, 47)
        .add(buttonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    panelButtonsLayout.setVerticalGroup(
      panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelButtonsLayout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(buttonCancel)
          .add(buttonStart)))
    );

    jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12));
    jLabel4.setText("Acquiring Sequence");

    labelInterval.setText("at interval (sec.):");

    valueInterval.setText("-");

    valueNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    valueNumber.setText("-");

    org.jdesktop.layout.GroupLayout panelTitleLayout = new org.jdesktop.layout.GroupLayout(panelTitle);
    panelTitle.setLayout(panelTitleLayout);
    panelTitleLayout.setHorizontalGroup(
      panelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelTitleLayout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(valueNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(14, 14, 14)
        .add(labelInterval)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(valueInterval, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(23, 23, 23))
    );
    panelTitleLayout.setVerticalGroup(
      panelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
        .add(jLabel4)
        .add(valueNumber)
        .add(valueInterval)
        .add(labelInterval))
    );

    panelStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    labalBegan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    labalBegan.setText("Began: 00:00:00");

    labelWillFinish.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelWillFinish.setText("Will finish: 00:00:00");

    labelToGo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    labelToGo.setText("To Go: 00:00:00");

    labelCompleted.setFont(new java.awt.Font("SansSerif", 0, 11));
    labelCompleted.setForeground(new java.awt.Color(0, 0, 204));
    labelCompleted.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelCompleted.setText("000 completed of 000 intervals");

    org.jdesktop.layout.GroupLayout panelStatusLayout = new org.jdesktop.layout.GroupLayout(panelStatus);
    panelStatus.setLayout(panelStatusLayout);
    panelStatusLayout.setHorizontalGroup(
      panelStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelStatusLayout.createSequentialGroup()
        .addContainerGap()
        .add(panelStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 306, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, panelStatusLayout.createSequentialGroup()
            .add(labelToGo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 61, Short.MAX_VALUE)
            .add(labelWillFinish, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(panelStatusLayout.createSequentialGroup()
            .add(labalBegan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(labelCompleted, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
        .addContainerGap())
    );
    panelStatusLayout.setVerticalGroup(
      panelStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelStatusLayout.createSequentialGroup()
        .addContainerGap()
        .add(panelStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(labalBegan)
          .add(labelCompleted))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(panelStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(labelWillFinish)
          .add(labelToGo))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
          .add(layout.createSequentialGroup()
            .add(10, 10, 10)
            .add(panelButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(panelStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
              .add(panelTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(panelClock, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(panelTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(panelStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jProgressBar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
          .add(panelClock, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(panelButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void CancelIt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelIt
      clock.cancel();
      seqCtrl.cancel();
      buttonCancel.setEnabled(false);
      String completed = "CANCELLED after " + String.valueOf(seqCtrl.getNDone()) + " invervals";
      labelCompleted.setText(completed);
      labelCompleted.setForeground(Color.red);
    }//GEN-LAST:event_CancelIt

    private void StartIt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartIt
      this.startSequence();
    }//GEN-LAST:event_StartIt

  public void allDone() {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        buttonCancel.setEnabled(false);
        jProgressBar1.setValue(seqCtrl.getIntervals());
        labelCompleted.setFont(new Font("Monospaced", Font.BOLD, 12));
        labelCompleted.setText(
                "Done acquiring " + String.valueOf(seqCtrl.getIntervals()) + " intervals.");
        if (clock != null) {
          clock.setDone();
        }
      }
    });
  }

  CountdownClock getClock() {
    return clock;
  }

  public void updateStatus() {
    SwingUtilities.invokeLater(new Runnable() {

      public void run() {
        labalBegan.setText("Began: " + Utils.timeFormat(
                seqCtrl.getBeganTime()));
        labelWillFinish.setText("To Finish: " + Utils.timeFormat(
                seqCtrl.getWillEndTime()));
        labelToGo.setText("To Go: " + Utils.durationHhMmSs(
                seqCtrl.getToGoTime()));
        String completed = String.valueOf(seqCtrl.getNDone()) + " completed of " +
                String.valueOf(seqCtrl.getIntervals()) + " intervals";
        labelCompleted.setText(completed);
        jProgressBar1.setValue(seqCtrl.getNDone());
      }
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonStart;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JProgressBar jProgressBar1;
  private javax.swing.JProgressBar jProgressBar2;
  private javax.swing.JLabel labalBegan;
  private javax.swing.JLabel labelCompleted;
  private javax.swing.JLabel labelInterval;
  private javax.swing.JLabel labelToGo;
  private javax.swing.JLabel labelWillFinish;
  private javax.swing.JPanel panelButtons;
  private javax.swing.JPanel panelClock;
  private javax.swing.JPanel panelStatus;
  private javax.swing.JPanel panelTitle;
  private javax.swing.JLabel valueInterval;
  private javax.swing.JLabel valueNumber;
  // End of variables declaration//GEN-END:variables
}
