/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelArcLC.java
 *
 * Created on Jun 30, 2009, 2:53:05 PM
 */
package edu.mbl.jif.oidic;

import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author GBH
 */
public class PanelArcLC extends javax.swing.JPanel {
ArcLC arcLC;
  /** Creates new form PanelArcLC */
  public PanelArcLC() {
    initComponents();
  }
  public PanelArcLC(ArcLC arcLC) {
    this.arcLC = arcLC;
    initComponents();
  }

  public void setArcLC(ArcLC arcLC ) {
    this.arcLC = arcLC;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    spinA = new javax.swing.JSpinner();
    jLabel2 = new javax.swing.JLabel();
    spinB = new javax.swing.JSpinner();

    jPanel1.setLayout(new java.awt.GridLayout(2, 2));

    jLabel1.setText("A");
    jPanel1.add(jLabel1);

    spinA.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));
    spinA.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        spinAStateChanged(evt);
      }
    });
    jPanel1.add(spinA);

    jLabel2.setText("B");
    jPanel1.add(jLabel2);

    spinB.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));
    spinB.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        spinBStateChanged(evt);
      }
    });
    jPanel1.add(spinB);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(78, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void spinAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinAStateChanged
      JSpinner spin = (JSpinner) evt.getSource();
      SpinnerNumberModel model = (SpinnerNumberModel) spin.getModel();
      System.out.println("A value is: " + model.getValue());
      double value = model.getNumber().doubleValue();
      arcLC.setDACVoltageA(value);
    }//GEN-LAST:event_spinAStateChanged

    private void spinBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinBStateChanged
      JSpinner spin = (JSpinner) evt.getSource();
      SpinnerNumberModel model = (SpinnerNumberModel) spin.getModel();
      System.out.println("B value is: " + model.getValue());
      double value = model.getNumber().doubleValue();
      arcLC.setDACVoltageB(value);
    }//GEN-LAST:event_spinBStateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSpinner spinA;
  private javax.swing.JSpinner spinB;
  // End of variables declaration//GEN-END:variables
}
