/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestJXErrorPane.java
 *
 * Created on Jan 21, 2009, 3:11:47 PM
 */
package edu.mbl.jif.swingx;

import javax.swing.JOptionPane;
import org.jdesktop.swingx.JXErrorPane;
import org.jdesktop.swingx.error.ErrorInfo;
import org.jdesktop.swingx.error.ErrorLevel;
import org.jdesktop.swingx.error.ErrorReporter;

/**
 *
 * @author GBH
 */
public class TestJXErrorPane extends javax.swing.JFrame {

    /** Creates new form TestJXErrorPane */
    public TestJXErrorPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TestJXErrorPane t = new TestJXErrorPane();
                t.setVisible(true);
                Exception exception = new Exception();
                JXErrorPane.showDialog(exception);


                // ErrorInfo errorInfo = new ErrorInfo(
//                        "File Corruption",
//                        "AppPro cannot open...",
//                        null, /*can be custom details instead*/
//                        "FileLoad", /*dovetails with logging*/
//                        exception,
//                        ErrorLevel.SEVERE,
//                        null); /*Map of additional state*/
                ErrorInfo errorInfo = new ErrorInfo(
                        "File Corruption",
                        "AppPro cannot open...",
                        "More details", // details
                        null, // catagory for logging
                        null,
                        ErrorLevel.FATAL,
                        null); /*Map of additional state*/
                //JXErrorPane.showFrame(t, errorInfo);
                JXErrorPane pane = new JXErrorPane();
                pane.setErrorInfo(errorInfo);
                ErrorReporter errorReporter;
                pane.setErrorReporter(new TestReporter());
                JXErrorPane.showDialog(null, pane);
            }
        });
    }

   static class TestReporter implements ErrorReporter {

        @Override
        public void reportError(ErrorInfo errInfo) throws NullPointerException {
            JOptionPane.showMessageDialog(null,
                    errInfo.getBasicErrorMessage(),
                    "An Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
