package tests.gui.NBFormExt;

/*
 * BeanPanelForm.java
 *
 * Created on June 26, 2002, 3:36 PM
 */

/**
 *
 * @author  tp105349
 */

public class ExtendingPanelForm extends BasePanelForm {

    
    /** Creates new form BeanForm */
    public ExtendingPanelForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
