/*
 * PanelVLC.java
 *
 * Created on June 1, 2006, 6:15 PM
 */

package edu.mbl.jif.laser;

import edu.mbl.jif.camacq.InstrumentController;
import edu.mbl.jif.camera.camacq.*;
import javax.swing.JPanel;

/**
 *
 * @author  GBH
 */
public class PanelSurgeon extends javax.swing.JPanel {
    private final InstrumentController ctrl;
    
    public PanelSurgeon(InstrumentController ctrl) {
        this.ctrl = ctrl;
        initComponents();
    }

    public void addTab(String label, JPanel panel) {
        jTabbedPane1.addTab(label, panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(233, 228, 218));

        jTabbedPane1.setBackground(new java.awt.Color(233, 226, 211));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
   
}
