/*
 * PanelStageLaserPath.java
 *
 * Created on September 26, 2008, 10:15 AM
 */

package edu.mbl.jif.laser;

/**
 *
 * @author  GBH
 */
public class PanelStageLaserPath extends javax.swing.JPanel {

    /** Creates new form PanelStageLaserPath */
    public PanelStageLaserPath() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    panelXYStage1 = new edu.mbl.jif.stage.PanelXYStage();
    panelLaser1 = new edu.mbl.jif.laser.PanelLaser();
    panelPath1 = new edu.mbl.jif.laser.PanelPath();

    setLayout(new java.awt.BorderLayout());

    jTabbedPane1.addTab("XYStage", panelXYStage1);
    jTabbedPane1.addTab("Laser", panelLaser1);
    jTabbedPane1.addTab("Path", panelPath1);

    add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    jTabbedPane1.getAccessibleContext().setAccessibleName("");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane jTabbedPane1;
  private edu.mbl.jif.laser.PanelLaser panelLaser1;
  private edu.mbl.jif.laser.PanelPath panelPath1;
  private edu.mbl.jif.stage.PanelXYStage panelXYStage1;
  // End of variables declaration//GEN-END:variables

}
