/*
 * PanelXYPositionDisplay.java
 *
 * Created on December 20, 2006, 5:10 PM
 */
package edu.mbl.jif.gui.spatial;

import edu.mbl.jif.gui.test.FrameForTest;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author  GBH
 */
public class PanelXYPositionDisplay
        extends javax.swing.JPanel {

    double width;
    double height;
    double x;
    double y;
    double viewW;
    double viewH;
    private double xScale;
    private double yScale;

    /** Creates new form PanelXYPositionDisplay */
    public PanelXYPositionDisplay() {
        initComponents();

    }

    public void setDimensions(double width, double height,
                              double viewW, double viewH) {
        positionPanel1.setDimensions(width, height, viewW, viewH);
    }

    public void updatePosition(double x, double y) {
        positionPanel1.updatePosition(x, y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        valueX = new javax.swing.JLabel();
        positionPanel1 = new edu.mbl.jif.gui.spatial.PositionPanel();

        setLayout(new java.awt.BorderLayout());

        valueX.setText("dx");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(valueX, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(valueX, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout positionPanel1Layout = new javax.swing.GroupLayout(positionPanel1);
        positionPanel1.setLayout(positionPanel1Layout);
        positionPanel1Layout.setHorizontalGroup(
            positionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        positionPanel1Layout.setVerticalGroup(
            positionPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        add(positionPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private edu.mbl.jif.gui.spatial.PositionPanel positionPanel1;
    private javax.swing.JLabel valueX;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        FrameForTest f = new FrameForTest();
        PanelXYPositionDisplay p = new PanelXYPositionDisplay();
        f.addContents(p);
        f.pack();
        f.setVisible(true);
        p.setDimensions(20.0, 20.0, 2.0, 2.0);
        p.updatePosition(10.0, 14.0);

    }

}

/*
 *   public void showROIs() {
DisplayLiveCamera fid = this.instrumentCtrl.getDisplayLive();
GraphicOverlay overlay1 = new GraphicOverlay() {

public void drawGraphicOverlay(ZoomGraphics zg) {
zg.setColor(Color.green);
for (int i = 0; i < retarderROIs.length; i++) {
drawArect(zg,
retarderROIs[i]);
}
}


public void drawArect(ZoomGraphics zg,
Rectangle rect) {
zg.drawRect(rect.getX(),
rect.getY(),
rect.getWidth(),
rect.getHeight());
}


};

fid.getImageDisplayPanel().imagePane.addGraphicOverlay(overlay1);

GraphicOverlay overlay2 = new GraphicOverlay() {

public void drawGraphicOverlay(ZoomGraphics zg) {
zg.setColor(Color.blue);
for (int i = 0; i < ellipticalROIs.length; i++) {
drawArect(zg,
ellipticalROIs[i]);
}
}


public void drawArect(ZoomGraphics zg,
Rectangle rect) {
zg.drawRect(rect.getX(),
rect.getY(),
rect.getWidth(),
rect.getHeight());
}


};

fid.getImageDisplayPanel().imagePane.addGraphicOverlay(overlay2);

GraphicOverlay overlay3 = new GraphicOverlay() {

public void drawGraphicOverlay(ZoomGraphics zg) {
zg.setColor(Color.red);
for (int i = 0; i < circularROIs.length; i++) {
drawArect(zg,
circularROIs[i]);
}
}


public void drawArect(ZoomGraphics zg,
Rectangle rect) {
zg.drawRect(rect.getX(),
rect.getY(),
rect.getWidth(),
rect.getHeight());
}


};
fid.getImageDisplayPanel().imagePane.addGraphicOverlay(overlay3);
}
 */
