/*
 * DataDirSelect.java
 *
 * Created on June 20, 2006, 10:43 AM
 */

package edu.mbl.jif.data;

import com.jgoodies.binding.value.ValueModel;
import com.l2fprod.common.swing.JDirectoryChooser;
import edu.mbl.jif.gui.file.DirectorySelector;
import java.awt.Component;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 * Generalized Directory Picker using ValueModel
 * @author  GBH
 */
public class DataFileSelect extends javax.swing.JPanel {
    
    ValueModel valueModel;
    String msg;
    Component parent;
    
    /** Creates new form DataDirSelect */
    public DataFileSelect(ValueModel valueModel, final Component parent) {
        this(valueModel, parent,  "Select data folder");
    }
    
    public DataFileSelect(ValueModel valueModel, final Component parent, String msg) {
        this.msg = msg;
        this.valueModel = valueModel;
        this.parent = parent;
        initComponents();
        fieldDir.setText((String)valueModel.getValue());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldDir = new javax.swing.JFormattedTextField();
        buttonChangeDir = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setText("  Data path:  ");
        add(jLabel1);

        fieldDir.setEditable(false);
        fieldDir.setMaximumSize(new java.awt.Dimension(200, 22));
        add(fieldDir);

        buttonChangeDir.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        buttonChangeDir.setText("...");
        buttonChangeDir.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonChangeDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDirChooser(evt);
            }
        });
        add(buttonChangeDir);
    }// </editor-fold>//GEN-END:initComponents
    
   private void openDirChooser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDirChooser
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               String dataPath = selectDirectory(null, null, msg, null);  // no confirmation
               if(dataPath != null) {
                   valueModel.setValue(dataPath);
                   fieldDir.setText(dataPath);
               }
           }
       });
   }//GEN-LAST:event_openDirChooser
   // Using l2prod...
   
   public static String selectDirectory(Component parent, String selectedFile,
           String message, String confirmMsg) {
       JDirectoryChooser chooser = new JDirectoryChooser();
       if (selectedFile != null) {
           chooser.setSelectedFile(new File(selectedFile));
       }
       JTextArea accessory = new JTextArea(message);
       accessory.setLineWrap(true);
       accessory.setWrapStyleWord(true);
       accessory.setEditable(false);
       accessory.setOpaque(false);
       accessory.setFont(UIManager.getFont("Tree.font"));
       chooser.setAccessory(accessory);
       chooser.setMultiSelectionEnabled(false); // <<<<<<<<
       int choice = chooser.showOpenDialog(parent);
       if (choice == JDirectoryChooser.APPROVE_OPTION) {
           String filenames = "";
           File[] selectedFiles = chooser.getSelectedFiles();
           for (int i = 0, c = selectedFiles.length; i < c; i++) {
               filenames += selectedFiles[i];
           }
           if(confirmMsg!=null) {
               JOptionPane.showMessageDialog(parent, confirmMsg + filenames);
           }
           return filenames;
       } else {
           if(confirmMsg!=null) {
               JOptionPane.showMessageDialog(parent, "Cancelled");
           }
           return null;
       }
   }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChangeDir;
    private javax.swing.JFormattedTextField fieldDir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
