copy %1\atmcd64d.dll                   %2
copy %1\FxLib.dll                      %2
copy %1\inpoutx64.dll                  %2
copy %1\LaserCombinerSDK64.dll         %2
copy %1\libusb0.dll                    %2
copy %1\lucamapi.dll                   %2
copy %1\mcammr64.dll                   %2
copy %1\MMCoreJ_wrap.dll               %2
copy %1\mmgr_dal_AndorSDK3.dll         %2
copy %1\mmgr_dal_DemoCamera.dll        %2
copy %1\mmgr_dal_FreeSerialPort.dll    %2
copy %1\mmgr_dal_Hamamatsu.dll         %2
copy %1\mmgr_dal_HamamatsuHam.dll      %2
copy %1\mmgr_dal_Lumenera.dll          %2
copy %1\mmgr_dal_Nikon.dll             %2
copy %1\mmgr_dal_NikonTE2000.dll       %2
copy %1\mmgr_dal_NikonTI.dll           %2
copy %1\mmgr_dal_QCam.dll              %2
copy %1\mmgr_dal_SerialManager.dll     %2
copy %1\mmgr_dal_SimpleAutofocus.dll   %2
copy %1\mmgr_dal_USBManager.dll        %2
copy %1\mmgr_dal_Utilities.dll         %2
copy %1\mmgr_dal_VariLC.dll            %2
copy %1\mmgr_dal_Vincent.dll           %2
copy %1\mrfw64.dll                     %2
copy %1\opencv_core231.dll             %2
copy %1\opencv_highgui231.dll          %2
copy %1\SysInfo.dll                    %2
copy %1\XCLIBW64.dll                   %2
copy %1\IJ_Prefs.txt                   %2
copy %1\ImageJ.cfg                     %2
copy %1\ImageJ.exe                     %2
copy %1\MMConfig_demo.cfg              %2

