/*
 * PanelShutterConfig.java
 *
 * Created on August 7, 2008, 8:46 AM
 */
package edu.mbl.jif.microscope.illum;

import edu.mbl.jif.camacq.InstrumentController;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author  GBH
 */
public class PanelShutterConfig extends javax.swing.JPanel {

    private final InstrumentController ctrl;

    public PanelShutterConfig(InstrumentController ctrl)
      {
        this.ctrl = ctrl;
        setIllumModel((IllumModel) ctrl.getModel("illum"));
        initComponents();
        bindShutterType();
      }

    /** Creates new form PanelShutterConfig */
    public void bindShutterType()
      {
        JComboBoxBinding b = SwingBindings.createJComboBoxBinding(
            org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, IlluminatorType.getIlluminatorTypeList(), comboBoxShutterType);
        b.bind();

        Binding b2 = Bindings.createAutoBinding(
            org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
            illumModel, BeanProperty.create("shutterTypeEpi"),
            comboBoxShutterType, BeanProperty.create("selectedItem"));
        b2.bind();
      }
    protected IllumModel illumModel;
    public static final String PROP_ILLUMMODEL = "illumModel";

    /**
     * Get the value of illumModel
     *
     * @return the value of illumModel
     */
    public IllumModel getIllumModel()
      {
        return illumModel;
      }

    /**
     * Set the value of illumModel
     *
     * @param illumModel new value of illumModel
     */
    public void setIllumModel(IllumModel illumModel)
      {
        IllumModel oldIllumModel = this.illumModel;
        this.illumModel = illumModel;
        propertyChangeSupport.firePropertyChange(PROP_ILLUMMODEL, oldIllumModel, illumModel);
      }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener)
      {
        propertyChangeSupport.addPropertyChangeListener(listener);
      }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener)
      {
        propertyChangeSupport.removePropertyChangeListener(listener);
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxShutterType = new javax.swing.JComboBox();

        comboBoxShutterType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(comboBoxShutterType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(comboBoxShutterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxShutterType;
    // End of variables declaration//GEN-END:variables
}
