/*
 * PanelDeviceConfig.java
 *
 * Created on April 12, 2007, 9:12 AM
 */

package edu.mbl.jif.comm;

/**
 *
 * @author  GBH
 */
public class PanelDeviceConfig extends javax.swing.JPanel {
    
    /** Creates new form PanelDeviceConfig */
    public PanelDeviceConfig(  ) {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        buttonSettings = new javax.swing.JButton();
        buttonMonitor = new javax.swing.JButton();
        checkEnabled = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Device"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/microscope/usb16.png"))); // NOI18N
        buttonSettings.setToolTipText("Port Setting");
        buttonSettings.setMargin(new java.awt.Insets(2, 4, 2, 4));
        buttonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSettingsActionPerformed(evt);
            }
        });

        buttonMonitor.setFont(new java.awt.Font("Tahoma", 0, 10));
        buttonMonitor.setText("COM1");
        buttonMonitor.setMargin(new java.awt.Insets(2, 4, 2, 4));

        checkEnabled.setText("enabled");
        checkEnabled.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkEnabled.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkEnabled)
                .addGap(14, 14, 14)
                .addComponent(buttonMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkEnabled)
                        .addComponent(buttonMonitor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonSettings, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSettingsActionPerformed

}//GEN-LAST:event_buttonSettingsActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMonitor;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JCheckBox checkEnabled;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
    
}
