/*
 * PanelConfigureVariLC.java
 *
 * Created on February 23, 2007, 12:44 AM
 */
package edu.mbl.jif.varilc;

import edu.mbl.jif.varilc.camacq.VariLCController;
import com.jgoodies.binding.adapter.BasicComponentFactory;
import com.jgoodies.binding.adapter.SpinnerAdapterFactory;
import edu.mbl.jif.camacq.InstrumentController;
import java.io.IOException;
import javax.swing.JSpinner;

/**
 *
 * @author  GBH
 */
public class PanelConfigureVariLC
        extends javax.swing.JPanel {

    VariLCModel vlcm;
    VariLCPresentation vlcp;
    InstrumentController ctrl;
    private VLCController vlcCtrl;


    /** Creates new form PanelConfigureVariLC */
    public PanelConfigureVariLC(InstrumentController ctrl) {
        this.ctrl = ctrl;
        this.vlcm = (VariLCModel) ctrl.getModel("variLC");
        vlcp = new VariLCPresentation(vlcm);
        this.vlcCtrl = (VLCController) ctrl.getController("variLC");
        initComponents();

        spinSettleTime.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_SETTLETIME),
                vlcp.getModel(VariLCModel.PROPERTYNAME_SETTLETIME).intValue(), // defaultValue
                0, 10000,
                10)); // step

        double minMaxStep = 0.01;
        spinAMin.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_MINA),
                vlcp.getModel(VariLCModel.PROPERTYNAME_MINA).doubleValue(), // defaultValue
                0.0, 1.0,
                minMaxStep)); // step
        spinAMax.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXA),
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXA).doubleValue(), // defaultValue
                0.0, 1.0,
                minMaxStep)); // step
        spinBMin.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_MINB),
                vlcp.getModel(VariLCModel.PROPERTYNAME_MINB).doubleValue(), // defaultValue
                0.0, 1.0,
                minMaxStep)); // step
        spinBMax.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXB),
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXB).doubleValue(), // defaultValue
                0.0, 1.0,
                minMaxStep)); // step
        spinMaxIters.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXITERATIONS),
                vlcp.getModel(VariLCModel.PROPERTYNAME_MAXITERATIONS).intValue(), // defaultValue
                1, 200,
                1)); // step

        spinTolFine.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_TOLERANCEFINE),
                vlcp.getModel(VariLCModel.PROPERTYNAME_TOLERANCEFINE).doubleValue(), // defaultValue
                0.00001, 10.0,
                0.00001)); // step
        ((JSpinner.NumberEditor) spinTolFine.getEditor()).getFormat().applyPattern("0.00000");
                

        spinTolGross.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_TOLERANCEGROSS),
                vlcp.getModel(VariLCModel.PROPERTYNAME_TOLERANCEGROSS).doubleValue(), // defaultValue
                0.00001, 10.0,
                0.00001)); // step
        ((JSpinner.NumberEditor) spinTolGross.getEditor()).getFormat().applyPattern("0.00000");

        spinStability.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_STABILITYLEVEL),
                vlcp.getModel(VariLCModel.PROPERTYNAME_STABILITYLEVEL).doubleValue(), // defaultValue
                0.0, 10.0,
                0.1)); // step

        spinWavelength.setModel(SpinnerAdapterFactory.createNumberAdapter(
                vlcp.getModel(VariLCModel.PROPERTYNAME_WAVELENGTH),
                vlcp.getModel(VariLCModel.PROPERTYNAME_WAVELENGTH).doubleValue(), // defaultValue
                VariLCModel.WAVELENGTH_MIN, VariLCModel.WAVELENGTH_MAX,
                10.0)); // step
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    spinSettleTime = new javax.swing.JSpinner();
    spinWavelength = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    spinAMin = new javax.swing.JSpinner();
    spinAMax = new javax.swing.JSpinner();
    jLabel6 = new javax.swing.JLabel();
    spinBMin = new javax.swing.JSpinner();
    spinBMax = new javax.swing.JSpinner();
    jPanel1 = new javax.swing.JPanel();
    buttonPortSettings = new javax.swing.JButton();
    buttonMonitor = new javax.swing.JButton();
    buttonReset = new javax.swing.JButton();
    buttonStatus = new javax.swing.JButton();
    buttonExercise = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    spinTolGross = new javax.swing.JSpinner();
    spinTolFine = new javax.swing.JSpinner();
    spinStability = new javax.swing.JSpinner();
    jLabel3 = new javax.swing.JLabel();
    spinMaxIters = new javax.swing.JSpinner();
    jLabel8 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(219, 219, 170));

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel3.setOpaque(false);

    spinSettleTime.setPreferredSize(new java.awt.Dimension(60, 18));

    spinWavelength.setPreferredSize(new java.awt.Dimension(60, 18));

    jLabel4.setText("Wavelength, nm");

    jLabel1.setText("SettleTime, msec");

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "(requires restart)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 8))); // NOI18N
    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.GridLayout(2, 3));

    jLabel5.setText("A    min/max");
    jPanel2.add(jLabel5);

    spinAMin.setPreferredSize(new java.awt.Dimension(50, 18));
    jPanel2.add(spinAMin);

    spinAMax.setPreferredSize(new java.awt.Dimension(50, 18));
    jPanel2.add(spinAMax);

    jLabel6.setText("B    min/max");
    jPanel2.add(jLabel6);

    spinBMin.setPreferredSize(new java.awt.Dimension(50, 18));
    jPanel2.add(spinBMin);

    spinBMax.setPreferredSize(new java.awt.Dimension(50, 18));
    jPanel2.add(spinBMax);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addGap(32, 32, 32)
            .addComponent(spinWavelength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(30, 30, 30)
            .addComponent(spinSettleTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(spinWavelength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel1))
          .addComponent(spinSettleTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel1.setOpaque(false);
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

    buttonPortSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/mbl/jif/comm/icons/usb16.png"))); // NOI18N
    buttonPortSettings.setToolTipText("Port Settings");
    buttonPortSettings.setMargin(new java.awt.Insets(2, 4, 2, 4));
    buttonPortSettings.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonPortSettingsActionPerformed(evt);
      }
    });
    jPanel1.add(buttonPortSettings);

    buttonMonitor.setText("Monitor");
    buttonMonitor.setMargin(new java.awt.Insets(2, 4, 2, 4));
    buttonMonitor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonMonitorActionPerformed(evt);
      }
    });
    jPanel1.add(buttonMonitor);

    buttonReset.setText(" Reset");
    buttonReset.setMargin(new java.awt.Insets(2, 4, 2, 4));
    buttonReset.setPreferredSize(new java.awt.Dimension(50, 23));
    buttonReset.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonResetActionPerformed(evt);
      }
    });
    jPanel1.add(buttonReset);

    buttonStatus.setText("Status?");
    buttonStatus.setMargin(new java.awt.Insets(2, 4, 2, 4));
    buttonStatus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonStatusActionPerformed(evt);
      }
    });
    jPanel1.add(buttonStatus);

    buttonExercise.setText("Exercise");
    buttonExercise.setMargin(new java.awt.Insets(2, 4, 2, 4));
    jPanel1.add(buttonExercise);

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Optimization"));

    jLabel2.setText("Gross/Fine Tol.");

    spinTolGross.setPreferredSize(new java.awt.Dimension(60, 18));

    spinTolFine.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0E-4d)));
    spinTolFine.setPreferredSize(new java.awt.Dimension(60, 18));

    jLabel3.setText("Stable");
    jLabel3.setToolTipText("Stability range");

    spinMaxIters.setPreferredSize(new java.awt.Dimension(50, 18));

    jLabel8.setText("MaxIter");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(spinMaxIters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel3)
            .addGap(12, 12, 12)
            .addComponent(spinStability))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(9, 9, 9)
            .addComponent(spinTolGross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(spinTolFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel2))
          .addComponent(spinTolGross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(spinTolFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(spinMaxIters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(spinStability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void buttonPortSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPortSettingsActionPerformed
      if(vlcCtrl instanceof VariLCController) {  
				VariLCController vlc = (VariLCController) vlcCtrl;
			if (vlc.openPortSettingsDialog(false)) {
            try {
                vlc.getSerialPortConnection().openConnection(vlc.PORT_OWNER_NAME);
                new Thread(new Runnable() {
                    public void run() {
                        vlcCtrl.setupVLC();//initializeController();
                    }
                }).start();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
			}
        }
    }//GEN-LAST:event_buttonPortSettingsActionPerformed


    private void buttonMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonitorActionPerformed
        if(vlcCtrl instanceof VariLCController) {  
				VariLCController vlc = (VariLCController) vlcCtrl;
				vlc.openMonitor();
				}
    }//GEN-LAST:event_buttonMonitorActionPerformed


    private void buttonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStatusActionPerformed
        vlcCtrl.statusCheck();
    }//GEN-LAST:event_buttonStatusActionPerformed


    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        vlcCtrl.reset();
    }//GEN-LAST:event_buttonResetActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonExercise;
  private javax.swing.JButton buttonMonitor;
  private javax.swing.JButton buttonPortSettings;
  private javax.swing.JButton buttonReset;
  private javax.swing.JButton buttonStatus;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JSpinner spinAMax;
  private javax.swing.JSpinner spinAMin;
  private javax.swing.JSpinner spinBMax;
  private javax.swing.JSpinner spinBMin;
  private javax.swing.JSpinner spinMaxIters;
  private javax.swing.JSpinner spinSettleTime;
  private javax.swing.JSpinner spinStability;
  private javax.swing.JSpinner spinTolFine;
  private javax.swing.JSpinner spinTolGross;
  private javax.swing.JSpinner spinWavelength;
  // End of variables declaration//GEN-END:variables
}
