/*
 * NuLooqForm.java
 *
 * Created on September 20, 2007, 1:52 PM
 */
package edu.mbl.jif.joystick;

import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author  GBH
 */
public class NuLooqForm extends javax.swing.JPanel implements XYInputListener {

    private double xSensitivity = 0.5;
    private int xThreshold = 10;
    private double xPos = 0;
    private double ySensitivity = 0.5;
    private int yThreshold = 10;
    private double yPos = 0;
    private double zRotSensitivity = 0.5;
    private int zRotThreshold = 200;
    private double zRot = 0;
    private XYPositionPanel panelXYPositionDisplay;
    private double xRange = 100000;
    private double yRange = 100000;
    private double zRotRange = 100000;

    /** Creates new form NuLooqForm */
    public NuLooqForm() {
        initComponents();
    }

    public NuLooqForm(XYPositionPanel panelXYPosition) {
        this.panelXYPositionDisplay = panelXYPosition;
        initComponents();
        this.add(panelXYPositionDisplay);
        panelXYPositionDisplay.setBounds(20, 200, 300, 300);
        panelXYPositionDisplay.setBackground(Color.lightGray);
    }

    @Override
    public void updateAxis(String name, double delta, double value) {
        if (name.equalsIgnoreCase("X Axis")) {
            if (Math.abs(delta) > this.xThreshold) {
                xPos = xPos + (-delta - xThreshold) * xSensitivity / xRange;
                valueX.setText(String.valueOf(xPos));
            }
        }
        if (name.equalsIgnoreCase("Y Axis")) {
            if (Math.abs(delta) > this.yThreshold) {
                yPos = yPos + (-delta - yThreshold) * ySensitivity / yRange;
                valueY.setText(String.valueOf(yPos));
            }
        }

        if (name.equalsIgnoreCase("Z Rotation")) {
            if (Math.abs(delta) > this.zRotThreshold) {
                zRot = zRot + (-delta - zRotThreshold) * zRotSensitivity / zRotRange;
                valueZRot.setText(String.valueOf(zRot));
                barZRot.setValue((int) (100 * zRot));
            }
        }
        panelXYPositionDisplay.update(xPos, yPos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      spinZRotThreshold = new javax.swing.JSpinner();
      sliderZRotSensitivity = new javax.swing.JSlider();
      valueZRotSensitivity = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      spinXYThreshold = new javax.swing.JSpinner();
      sliderXYSensitivity = new javax.swing.JSlider();
      valueXYSensitivity = new javax.swing.JLabel();
      checkXYFlip = new javax.swing.JCheckBox();
      checkZRotFlip = new javax.swing.JCheckBox();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      valueX = new javax.swing.JLabel();
      valueY = new javax.swing.JLabel();
      barZRot = new javax.swing.JProgressBar();
      valueZRot = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jLabel3.setText("Z-axis");

      spinZRotThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spinZRotThresholdStateChanged(evt);
         }
      });

      sliderZRotSensitivity.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            sliderZRotSensitivityStateChanged(evt);
         }
      });

      valueZRotSensitivity.setText("-");

      jLabel2.setText("X & Y axes");

      spinXYThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spinXYThresholdStateChanged(evt);
         }
      });

      sliderXYSensitivity.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            sliderXYSensitivityStateChanged(evt);
         }
      });

      valueXYSensitivity.setText("-");

      checkXYFlip.setText("flip");

      checkZRotFlip.setText("flip");

      jLabel6.setText("Threshold");

      jLabel7.setText("Sensitivity");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(spinZRotThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(sliderZRotSensitivity, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(8, 8, 8)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinXYThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderXYSensitivity, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(valueXYSensitivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(valueZRotSensitivity, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(checkXYFlip)
               .addComponent(checkZRotFlip))
            .addContainerGap(48, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel2)
                  .addComponent(spinXYThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(sliderXYSensitivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(valueXYSensitivity)
                  .addComponent(checkXYFlip)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(valueZRotSensitivity)
                  .addComponent(checkZRotFlip))
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(spinZRotThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel3))
               .addComponent(sliderZRotSensitivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      valueX.setText("X");

      valueY.setText("Y");

      valueZRot.setText("ZRot");

      jLabel1.setText("X");

      jLabel4.setText("Y");

      jLabel5.setText("Z rotation");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(valueX, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(valueY, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addGap(41, 41, 41)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(barZRot, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                  .addComponent(valueZRot)
                  .addGap(47, 47, 47))))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jLabel4)
               .addComponent(valueZRot)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(barZRot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(valueX)
                  .addComponent(valueY)))
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(321, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

    private void sliderXYSensitivityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderXYSensitivityStateChanged
        xSensitivity = (double) sliderXYSensitivity.getValue() / 100;
        ySensitivity = xSensitivity;
        valueXYSensitivity.setText(String.valueOf(xSensitivity));
}//GEN-LAST:event_sliderXYSensitivityStateChanged

    private void spinXYThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinXYThresholdStateChanged
        xThreshold = Integer.parseInt(((Integer) spinXYThreshold.getValue()).toString());
        yThreshold = xThreshold;
}//GEN-LAST:event_spinXYThresholdStateChanged

    private void spinZRotThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinZRotThresholdStateChanged
        zRotThreshold = Integer.parseInt(((Integer) spinZRotThreshold.getValue()).toString());
}//GEN-LAST:event_spinZRotThresholdStateChanged

private void sliderZRotSensitivityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderZRotSensitivityStateChanged
    zRotSensitivity = (double) sliderZRotSensitivity.getValue() / 100;
    valueZRotSensitivity.setText(String.valueOf(zRotSensitivity));
}//GEN-LAST:event_sliderZRotSensitivityStateChanged
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JProgressBar barZRot;
   private javax.swing.JCheckBox checkXYFlip;
   private javax.swing.JCheckBox checkZRotFlip;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JSlider sliderXYSensitivity;
   private javax.swing.JSlider sliderZRotSensitivity;
   private javax.swing.JSpinner spinXYThreshold;
   private javax.swing.JSpinner spinZRotThreshold;
   private javax.swing.JLabel valueX;
   private javax.swing.JLabel valueXYSensitivity;
   private javax.swing.JLabel valueY;
   private javax.swing.JLabel valueZRot;
   private javax.swing.JLabel valueZRotSensitivity;
   // End of variables declaration//GEN-END:variables
}