/*
 * PanelSerialParmsSetting.java
 *
 * Created on November 16, 2007, 11:34 AM
 */

package edu.mbl.jif.comm;

/**
 *
 * @author  GBH
 */
public class PanelSerialParmsSetting extends javax.swing.JPanel {
    
    /** Creates new form PanelSerialParmsSetting */
    public PanelSerialParmsSetting() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel6 = new javax.swing.JLabel();
    jComboBox5 = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jComboBox3 = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    jComboBox6 = new javax.swing.JComboBox();
    jLabel7 = new javax.swing.JLabel();
    jComboBox7 = new javax.swing.JComboBox();
    jLabel4 = new javax.swing.JLabel();
    jComboBox4 = new javax.swing.JComboBox();

    setBackground(new java.awt.Color(206, 206, 233));
    setLayout(new java.awt.GridLayout(3, 4, 4, 1));

    jLabel6.setText("Baud Rate ");
    add(jLabel6);

    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox5);

    jLabel2.setText("Data Bits");
    add(jLabel2);

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox2);

    jLabel3.setText("Stop Bits");
    add(jLabel3);

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox3);

    jLabel5.setText("Parity");
    add(jLabel5);

    jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox6);

    jLabel7.setText("Flow Ctrl-In");
    jLabel7.setPreferredSize(new java.awt.Dimension(64, 14));
    add(jLabel7);

    jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox7);

    jLabel4.setText("Flow Ctrl-Out ");
    add(jLabel4);

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    add(jComboBox4);
  }// </editor-fold>//GEN-END:initComponents
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JComboBox jComboBox3;
  private javax.swing.JComboBox jComboBox4;
  private javax.swing.JComboBox jComboBox5;
  private javax.swing.JComboBox jComboBox6;
  private javax.swing.JComboBox jComboBox7;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  // End of variables declaration//GEN-END:variables
    
}
