/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelLightpath.java
 *
 * Created on Jun 26, 2009, 1:55:26 PM
 */
package edu.mbl.jif.acq.mode;

import com.jgoodies.binding.adapter.BasicComponentFactory;
import edu.mbl.jif.acq.AcqModel;
import edu.mbl.jif.camacq.InstrumentController;

/**
 *
 * @author GBH
 */
public class PanelLightpath extends javax.swing.JPanel {

  private final InstrumentController ctrl;
  private final AcqModel.AcqPresentation acqPresentation;

  /**
   * Creates new form PanelAcq
   */
  public PanelLightpath(InstrumentController ctrl) {
    this.ctrl = ctrl;
    this.acqPresentation = new AcqModel.AcqPresentation((AcqModel) ctrl.getModel("acq"));
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    comboFilter = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    checkboxEpi = BasicComponentFactory.createCheckBox(acqPresentation.getModel(AcqModel.PROPERTYNAME_OPENSHUTTEREPI), "Epi");
    checkboxXmis = BasicComponentFactory.createCheckBox(acqPresentation.getModel(AcqModel.PROPERTYNAME_OPENSHUTTERXMIS), "Xmis");

    comboFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel3.setText("Filter");

    jLabel7.setText("Shutter");

    checkboxEpi.setText("Epi");

    checkboxXmis.setText("Xmis");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(checkboxXmis)
          .addComponent(checkboxEpi)
          .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(checkboxEpi))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(checkboxXmis)
        .addGap(15, 15, 15)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox checkboxEpi;
  private javax.swing.JCheckBox checkboxXmis;
  private javax.swing.JComboBox comboFilter;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel7;
  // End of variables declaration//GEN-END:variables
}
