/*
 * PanelIllum.java
 *
 * Created on May 29, 2006, 8:04 AM
 */

package edu.mbl.jif.microscope;

import com.jgoodies.binding.PresentationModel;
import com.jgoodies.binding.adapter.BasicComponentFactory;
import com.jgoodies.binding.adapter.BoundedRangeAdapter;
import com.jgoodies.binding.adapter.ToggleButtonAdapter;
import com.jgoodies.binding.value.ConverterFactory;
import edu.mbl.jif.camacq.InstrumentController;
import edu.mbl.jif.microscope.illum.IllumModel;
import java.text.NumberFormat;

/**
 *
 * @author  GBH
 */
public class PanelIllum extends javax.swing.JPanel {
    private final InstrumentController ctrl;
    private final IllumModel illumModel;
    private final PresentationModel illumPresentation;
    
    
    public PanelIllum(InstrumentController ctrl) {
        this.ctrl = ctrl;
        this.illumModel = (IllumModel)ctrl.getModel("illum");
        this.illumPresentation = new PresentationModel(illumModel);
        initComponents();
        // Epi Shutter
        sliderEpi.setModel(new BoundedRangeAdapter(
                ConverterFactory.createDoubleToIntegerConverter(
                illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_LEVELEPI), 100),
                0, 0, 100));
        toggleShutterEpi.setModel(new ToggleButtonAdapter(
                illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_OPENEPI)));
        // Xmission Shutter
        sliderXmiss.setModel(new BoundedRangeAdapter(
                ConverterFactory.createDoubleToIntegerConverter(
                illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_LEVELXMIS), 100),
                0, 0, 100));
        toggleShutterXmiss.setModel(new ToggleButtonAdapter(
                illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_OPENXMIS)));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    sliderXmiss = new javax.swing.JSlider();
    valueLevelXmis = BasicComponentFactory.createLabel(ConverterFactory.createStringConverter(
      illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_LEVELXMIS), NumberFormat.getNumberInstance()));
  toggleShutterXmiss = new javax.swing.JToggleButton();
  jPanel2 = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  sliderEpi = new javax.swing.JSlider();
  valueLevelEpi = BasicComponentFactory.createLabel(ConverterFactory.createStringConverter(
    illumPresentation.getComponentModel(IllumModel.PROPERTYNAME_LEVELEPI), NumberFormat.getNumberInstance()));
toggleShutterEpi = new javax.swing.JToggleButton();

setBackground(new java.awt.Color(237, 237, 200));

jPanel1.setBackground(new java.awt.Color(255, 255, 204));
jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
jLabel2.setText("Trans");
jLabel2.setMaximumSize(new java.awt.Dimension(50, 15));
jLabel2.setPreferredSize(new java.awt.Dimension(50, 15));
jPanel1.add(jLabel2);

sliderXmiss.setPaintLabels(true);
sliderXmiss.setMaximumSize(new java.awt.Dimension(200, 24));
sliderXmiss.setMinimumSize(new java.awt.Dimension(200, 24));
sliderXmiss.setOpaque(false);
jPanel1.add(sliderXmiss);

valueLevelXmis.setMaximumSize(new java.awt.Dimension(32, 16));
valueLevelXmis.setMinimumSize(new java.awt.Dimension(32, 16));
valueLevelXmis.setPreferredSize(new java.awt.Dimension(32, 16));
jPanel1.add(valueLevelXmis);

toggleShutterXmiss.setText("Shutter");
toggleShutterXmiss.setMargin(new java.awt.Insets(2, 4, 2, 4));
jPanel1.add(toggleShutterXmiss);

jPanel2.setBackground(new java.awt.Color(255, 255, 204));
jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
jLabel1.setText("Epi");
jLabel1.setMaximumSize(new java.awt.Dimension(50, 15));
jLabel1.setPreferredSize(new java.awt.Dimension(50, 15));
jPanel2.add(jLabel1);

sliderEpi.setMaximumSize(new java.awt.Dimension(200, 24));
sliderEpi.setMinimumSize(new java.awt.Dimension(200, 24));
sliderEpi.setOpaque(false);
jPanel2.add(sliderEpi);

valueLevelEpi.setMaximumSize(new java.awt.Dimension(32, 16));
valueLevelEpi.setMinimumSize(new java.awt.Dimension(32, 16));
valueLevelEpi.setPreferredSize(new java.awt.Dimension(32, 16));
jPanel2.add(valueLevelEpi);

toggleShutterEpi.setText("Shutter");
toggleShutterEpi.setMargin(new java.awt.Insets(2, 4, 2, 4));
jPanel2.add(toggleShutterEpi);

org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
this.setLayout(layout);
layout.setHorizontalGroup(
  layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
  .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
    .addContainerGap()
    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
      .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
      .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
  );
  layout.setVerticalGroup(
    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
    .add(layout.createSequentialGroup()
      .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
      .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
  );
  }// </editor-fold>//GEN-END:initComponents
                
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSlider sliderEpi;
  private javax.swing.JSlider sliderXmiss;
  private javax.swing.JToggleButton toggleShutterEpi;
  private javax.swing.JToggleButton toggleShutterXmiss;
  private javax.swing.JLabel valueLevelEpi;
  private javax.swing.JLabel valueLevelXmis;
  // End of variables declaration//GEN-END:variables
    
}
