/*
 * OkCancelDialog.java
 *
 * Created on November 27, 2007, 10:34 AM
 */
package edu.mbl.jif.gui.dialog;

import java.awt.BorderLayout;
import java.awt.Dialog;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author  GBH
 */
public class DialogOkCancel extends javax.swing.JDialog {

	/** A return status code - returned if Cancel button has been pressed */
	public static final int RET_CANCEL = 0;
	/** A return status code - returned if OK button has been pressed */
	public static final int RET_OK = 1;

	/** Creates new form OkCancelDialog */
	public DialogOkCancel(java.awt.Window parent, String title, Dialog.ModalityType modal) {
		super(parent, title, modal);
		initComponents();
	}

	public DialogOkCancel(java.awt.Frame parent, String title, boolean modal) {
		super(parent, modal);
		super.setTitle(title);
		initComponents();
	}

	/** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
	public int getReturnStatus() {
		return returnStatus;
	}

	public void addPanel(JComponent panel) {
		this.remove(panelOkCancel);
		this.add(panel, BorderLayout.CENTER);
		this.add(panelOkCancel, BorderLayout.SOUTH);
		this.pack();
	}

	public void enableOKButton(final boolean t) {
		okButton.setEnabled(t);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelOkCancel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelOkCancelLayout = new javax.swing.GroupLayout(panelOkCancel);
    panelOkCancel.setLayout(panelOkCancelLayout);
    panelOkCancelLayout.setHorizontalGroup(
      panelOkCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelOkCancelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cancelButton)
        .addContainerGap())
    );

    panelOkCancelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    panelOkCancelLayout.setVerticalGroup(
      panelOkCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelOkCancelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelOkCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    getContentPane().add(panelOkCancel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	  doClose(RET_OK);
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
	  doClose(RET_CANCEL);
  }//GEN-LAST:event_cancelButtonActionPerformed

	/** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
	  doClose(RET_CANCEL);
  }//GEN-LAST:event_closeDialog

	private void doClose(int retStatus) {
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				DialogOkCancel dialog =	new DialogOkCancel(new javax.swing.JFrame(), "Title...", true);
				JPanel panel = new JPanel();
				panel.add(new JLabel("The Label"));
				dialog.addPanel(panel);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton okButton;
  private javax.swing.JPanel panelOkCancel;
  // End of variables declaration//GEN-END:variables
	private int returnStatus = RET_CANCEL;
}
