package edu.mbl.jif.gui.file;
/*
 * FileSelectionPanel.java
 *
 * Created on February 16, 2006, 6:00 PM
 */

//import edu.mbl.jif.utils.file.FileChooserFixWinZip;
import edu.mbl.jif.gui.file.FileFilterStyler;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.Hashtable;
import java.util.Enumeration;
import javax.swing.*;
import javax.swing.filechooser.*;
//import org.jdesktop.swingx.JXFrame;

/**
 *
 * 
 * @author  GBH
 */
public class FileSelectionPanel extends javax.swing.JPanel {

    String ext = null;
    String msg = null;
    String defaultDir;
    String filepath = null;
    FileFilterStyler filter;
    //  ++ remember last file & dir
    String lastPath;

    public FileSelectionPanel() {
        initComponents();
    }

    /** Creates new form FileSelectionPanel */
    public FileSelectionPanel(String filepath, String defaultDir, FileFilterStyler filter, String msg) {
    }

    // single file extension
    public FileSelectionPanel(String defaultDir, String ext, String msg) {
        this.defaultDir = defaultDir;
        this.msg = msg;
        this.ext = ext;
        initComponents();
    }

    public void setFilepath(String fp) {
        filepath = fp;
        textFieldFilepath.setText(fp);
    }

    public String getFilepath() {
        return filepath;
    }

    public static void main(String[] args) {
        // FileChooserFixWinZip.applyFileChooserTweak();
        JFrame f = new JFrame("File");
        f.add(new FileSelectionPanel(null, "tif", "Tiff"));
				f.setPreferredSize(new Dimension(200, 65));
        f.pack();
        f.setVisible(true);
        // (new FileSelectionPanel("tif", "Tiff")).test();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      textFieldFilepath = new javax.swing.JTextField();
      buttonChooseFile = new javax.swing.JButton();

      setOpaque(false);
      setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

      textFieldFilepath.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
      textFieldFilepath.setText("file");
      add(textFieldFilepath);

      buttonChooseFile.setText("...");
      buttonChooseFile.setMargin(new java.awt.Insets(2, 4, 2, 4));
      buttonChooseFile.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ChooseFile(evt);
         }
      });
      add(buttonChooseFile);
   }// </editor-fold>//GEN-END:initComponents

    private void ChooseFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseFile
        JFileChooser fc = new JFileChooser();
        File file;
        JComponent frame = null;
        // Popup the fileChooser
        fc.resetChoosableFileFilters();
        filter = new FileFilterStyler(new String(ext));
        fc.addChoosableFileFilter(filter);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
				if(defaultDir == null) {
					defaultDir = ".";
				}
				File dir = new File(this.defaultDir);
				if(!dir.exists() || !dir.isDirectory()) {
					JOptionPane.showMessageDialog(frame, "Directory non-existant or not directory", "", 
							JOptionPane.WARNING_MESSAGE);
						setFilepath(null);
						return;
				}
        try {
            fc.setCurrentDirectory(new File(new File(defaultDir).getCanonicalPath()));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        fc.setSelectedFile(null);
        fc.setDialogTitle(msg);
        int returnVal = fc.showOpenDialog(frame);
        // get the fileChooser's selection
        file = null;
        if (returnVal != JFileChooser.APPROVE_OPTION) {
            return;
        }
        file = fc.getSelectedFile();
				if (file == null) {
            JOptionPane.showMessageDialog(frame, "null file ", "", JOptionPane.WARNING_MESSAGE);
						setFilepath(null);
						return;
        }
        if (!file.exists()) {
            JOptionPane.showMessageDialog(frame, "File " + file.toString() + " does not exist", "",
                    JOptionPane.WARNING_MESSAGE);
						setFilepath(null);
            return;
        }
        setFilepath(file.getAbsolutePath());
        
    }//GEN-LAST:event_ChooseFile
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonChooseFile;
   private javax.swing.JTextField textFieldFilepath;
   // End of variables declaration//GEN-END:variables
}
